### ISSUE TITLE
成績のチャートが欲しい

### ISSUE THREAD

**Issue by himkt** [makky3939/EscapeGoat#61]
欲しくない？

A+ : 40
A   : 30
B   : 20
C   : 10
D   : 5
みたいな情報を視覚化するもの

**Comment by makky3939** [comment]
:+1: 

可視化するので思いつくのは
- 学期ごとの累積単位数
- 任意の期間の各成績の棒グラフ
- 専門科目の単位数での棒グラフ（or円グラフ）
- 学類毎の単位数での棒グラフ（or円グラフ）

あたりですが欲しいグラフはありますか？

https://github.com/makky3939/GPA ではこんなのを作っていました（2番目に当たるやつです）

<img width="573" alt="screenshot 2016-01-19 14 37 56" src="https://cloud.githubusercontent.com/assets/4876459/12410626/6af29c1e-beba-11e5-96f6-abbfc6ca9740.png">

**Comment by himkt** [comment]
@makky3939 僕が意図していたのは https://github.com/makky3939/GPA をまま本体に実装する案です．

加えて適当に検索クエリを投げて，クエリにマッチした科目の成績の割合が見られたら面白いかもしれない？（「プログラミング」で検索してヒットした科目たちの成績分布がわかれば自分がどんな領域が得意でどんな領域が苦手かわかるかもしれない）

**Comment by makky3939** [comment]
fmfm

グラフは秋Cの成績開示までに実装します。

> 検索クエリを投げて

なるほど、グラフ書くときに絞込とかも出来るようにしてみます。

（現状だと成績データは割とロックな持ち方しているので（検索とかのAPIは持っていない）、Utilかnpmに切り分けてしまおうと思ってます。 #62）

**Comment by himkt** [comment]
:+1:
